--- #YAML:1.0
name:               DMTF-CIM-WSMan
version:            v0.04
abstract:           Provies WSMan CIM binding
author:
    - Stephen James Hurd <shurd@broadcom.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime::Duration:   0
    DMTF::CIM:            0
    DMTF::CIM::Instance:  0
    DMTF::WSMan:          0
    MIME::Base64:         0
    Test::More:           0
    URI:                  0
    URI::Escape:          0
    version:              0
    XML::Twig:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
